import React, { useEffect, useState } from "react";
import { exec } from "kernelsu";
import locate from "./locate.json";
import "./index.css";

type Lang = keyof typeof locate; // "en" | "zh"
type Tab = "config" | "rules" | "log";

// --- Config Types ---
type ConfigState = {
  moduledir: string;
  tempdir: string;
  mountsource: string;
  logfile: string;
  verbose: boolean;
  partitions: string[];
};

const DEFAULT_CONFIG: ConfigState = {
  moduledir: "/data/adb/modules",
  tempdir: "",
  mountsource: "KSU",
  logfile: "/data/adb/magic_mount/mm.log",
  verbose: false,
  partitions: [],
};

const CONFIG_PATH = "/data/adb/magic_mount/mm.conf";
const HYBRID_CONFIG_PATH = "/data/adb/magic_mount/hybrid.conf";

// --- Rule Types ---
type RuleMode = "overlay" | "bind";
type HybridRule = {
  path: string;
  mode: RuleMode;
};

const App: React.FC = () => {
  // ---------- i18n ----------
  const [lang, setLang] = useState<Lang>(() => {
    if (typeof window === "undefined") return "en";
    const saved = window.localStorage.getItem("mm-lang");
    return saved === "zh" || saved === "en" ? (saved as Lang) : "en";
  });
  const L = locate[lang];

  const handleLangChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const value = e.target.value as Lang;
    setLang(value);
    if (typeof window !== "undefined") {
      window.localStorage.setItem("mm-lang", value);
    }
  };

  // ---------- tabs ----------
  const [activeTab, setActiveTab] = useState<Tab>("config");

  // ---------- config state ----------
  const [config, setConfig] = useState<ConfigState>(DEFAULT_CONFIG);
  const [configLoading, setConfigLoading] = useState(false);
  const [configSaving, setConfigSaving] = useState(false);
  const [configMessage, setConfigMessage] = useState<string | null>(null);

  // ---------- rules state ----------
  const [rules, setRules] = useState<HybridRule[]>([]);
  const [rulesLoading, setRulesLoading] = useState(false);
  const [rulesSaving, setRulesSaving] = useState(false);
  const [rulesMessage, setRulesMessage] = useState<string | null>(null);

  // ---------- log state ----------
  type LogSelection = "current" | "old";
  const [logSelection, setLogSelection] = useState<LogSelection>("current");
  const [logContent, setLogContent] = useState("");
  const [logLoading, setLogLoading] = useState(false);
  const [logError, setLogError] = useState<string | null>(null);

  // ---------- partitions input ----------
  const [partitionInput, setPartitionInput] = useState("");

  // ---------- helpers ----------
  const isTrueValue = (v: string): boolean => {
    const s = v.trim().toLowerCase();
    return s === "1" || s === "true" || s === "yes" || s === "on";
  };

  const parseKvConfig = (text: string): ConfigState | null => {
    try {
      const result: ConfigState = { ...DEFAULT_CONFIG };
      const lines = text.split("\n");

      for (let line of lines) {
        line = line.trim();
        if (!line || line.startsWith("#")) continue;

        const eqIndex = line.indexOf("=");
        if (eqIndex < 0) {
          continue;
        }

        let key = line.slice(0, eqIndex).trim();
        let value = line.slice(eqIndex + 1).trim();

        if (!key || !value) continue;

        switch (key) {
          case "module_dir":
            result.moduledir = value;
            break;
          case "temp_dir":
            result.tempdir = value;
            break;
          case "mount_source":
            result.mountsource = value;
            break;
          case "log_file":
            result.logfile = value;
            break;
          case "debug":
            result.verbose = isTrueValue(value);
            break;
          case "partitions":
            result.partitions = value
              .split(",")
              .map((s) => s.trim())
              .filter((s) => s.length > 0);
            break;
          default:
            // unknown key: ignore
            break;
        }
      }

      return result;
    } catch (e) {
      console.error("Failed to parse config:", e);
      return null;
    }
  };

  const serializeKvConfig = (cfg: ConfigState): string => {
    const lines: string[] = ["# Magic Mount Configuration File", "# Generated by Web UI", ""];

    const moduleDir = cfg.moduledir || DEFAULT_CONFIG.moduledir;
    const mountSource = cfg.mountsource || DEFAULT_CONFIG.mountsource;
    const logFile = cfg.logfile || DEFAULT_CONFIG.logfile;

    lines.push(`module_dir=${moduleDir}`);

    if (cfg.tempdir) {
      lines.push(`temp_dir=${cfg.tempdir}`);
    }

    lines.push(`mount_source=${mountSource}`);

    if (logFile) {
      lines.push(`log_file=${logFile}`);
    }

    lines.push(`debug=${cfg.verbose ? "true" : "false"}`);

    if (cfg.partitions.length > 0) {
      lines.push(`partitions=${cfg.partitions.join(",")}`);
    }

    return lines.join("\n");
  };

  // ---------- read config ----------
  const loadConfig = async () => {
    setConfigLoading(true);
    setConfigMessage(null);

    try {
      const { errno, stdout, stderr } = await exec(
        `[ -f "${CONFIG_PATH}" ] && cat "${CONFIG_PATH}" || echo ""`,
      );

      if (errno !== 0) {
        console.error(stderr);
        setConfig(DEFAULT_CONFIG);
        setPartitionInput("");
        setConfigMessage(L.config.loadError);
        return;
      }

      if (!stdout.trim()) {
        setConfig(DEFAULT_CONFIG);
        setPartitionInput("");
        setConfigMessage(L.config.loadDefault);
        return;
      }

      const parsed = parseKvConfig(stdout);
      if (parsed) {
        setConfig(parsed);
        setPartitionInput(parsed.partitions.join(", "));
        setConfigMessage(L.config.loadSuccess);
      } else {
        setConfig(DEFAULT_CONFIG);
        setPartitionInput("");
        setConfigMessage(L.config.loadError);
      }
    } catch (e) {
      console.error(e);
      setConfig(DEFAULT_CONFIG);
      setPartitionInput("");
      setConfigMessage(L.config.loadError);
    } finally {
      setConfigLoading(false);
    }
  };

  // ---------- save config ----------
  const saveConfig = async () => {
    setConfigSaving(true);
    setConfigMessage(null);

    try {
      const partitions = partitionInput
        .split(",")
        .map((s) => s.trim())
        .filter((s) => s);

      const configToSave: ConfigState = { ...config, partitions };

      const content = serializeKvConfig(configToSave);
      // simple escape for single quotes
      const escapedContent = content.replace(/'/g, "'\\''");

      const shell = `
        mkdir -p "$(dirname "${CONFIG_PATH}")" && \
        printf '%s\n' '${escapedContent}' > "${CONFIG_PATH}"
      `;

      const { errno, stderr } = await exec(shell);

      if (errno !== 0) {
        console.error(stderr);
        setConfigMessage(L.config.saveFailed);
      } else {
        setConfig(configToSave);
        setConfigMessage(L.config.saveSuccess);
      }
    } catch (e) {
      console.error(e);
      setConfigMessage(L.config.saveError);
    } finally {
      setConfigSaving(false);
    }
  };

  // ---------- read rules ----------
  const loadRules = async () => {
    setRulesLoading(true);
    setRulesMessage(null);
    try {
      const { errno, stdout } = await exec(
        `[ -f "${HYBRID_CONFIG_PATH}" ] && cat "${HYBRID_CONFIG_PATH}" || echo ""`,
      );

      if (errno !== 0) {
        setRules([]);
        return;
      }

      const newRules: HybridRule[] = [];
      const lines = stdout.split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) continue;
        const parts = trimmed.split("|");
        if (parts.length === 2) {
          const path = parts[0].trim();
          const modeStr = parts[1].trim().toLowerCase();
          if (modeStr === "overlay" || modeStr === "bind") {
            newRules.push({ path, mode: modeStr as RuleMode });
          }
        }
      }
      setRules(newRules);
    } catch (e) {
      console.error(e);
    } finally {
      setRulesLoading(false);
    }
  };

  // ---------- save rules ----------
  const saveRules = async () => {
    setRulesSaving(true);
    setRulesMessage(null);
    try {
      let content = "# Hybrid Mount Rules\n# Path|Mode\n\n";
      for (const r of rules) {
        if (r.path.trim()) {
          content += `${r.path.trim()}|${r.mode}\n`;
        }
      }
      const escaped = content.replace(/'/g, "'\\''");
      const shell = `
        mkdir -p "$(dirname "${HYBRID_CONFIG_PATH}")" && \
        printf '%s\n' '${escaped}' > "${HYBRID_CONFIG_PATH}"
      `;
      const { errno, stderr } = await exec(shell);
      if (errno !== 0) {
        console.error(stderr);
        setRulesMessage(L.rules.saveFailed);
      } else {
        setRulesMessage(L.rules.saveSuccess);
      }
    } catch (e) {
      console.error(e);
      setRulesMessage(L.rules.saveFailed);
    } finally {
      setRulesSaving(false);
    }
  };

  // ---------- read log ----------
  const loadLog = async () => {
    setLogLoading(true);
    setLogError(null);
    setLogContent("");
    try {
      const basePath = config.logfile || DEFAULT_CONFIG.logfile;
      const fullPath = logSelection === "current" ? basePath : `${basePath}.old`;

      const { errno, stdout, stderr } = await exec(
        `[ -f "${fullPath}" ] && cat "${fullPath}" || echo "Log file not found"`,
      );

      if (errno !== 0) {
        console.error(stderr);
        setLogError(L.logs.readFailed + ` (errno=${errno})`);
      } else {
        setLogContent(stdout || "");
      }
    } catch (e) {
      console.error(e);
      setLogError(L.logs.readException);
    } finally {
      setLogLoading(false);
    }
  };

  // initial load
  useEffect(() => {
    loadConfig();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // reload data when tab changed
  useEffect(() => {
    if (activeTab === "log") {
      loadLog();
    } else if (activeTab === "rules") {
      loadRules();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeTab, logSelection]);

  // ---------- render tabs ----------

  const renderConfigTab = () => (
    <div className="card">
      <h2>{L.config.title}</h2>

      {configLoading && <p className="hint">Loading...</p>}
      {configMessage && <p className="hint">{configMessage}</p>}

      {/* Verbose switch */}
      <div className="field">
        <label>{L.config.verboseLabel}</label>
        <div className="loglevel-switch">
          <button
            className={!config.verbose ? "lv-btn active" : "lv-btn"}
            onClick={() =>
              setConfig((prev) => ({
                ...prev,
                verbose: false,
              }))
            }
          >
            {L.config.verboseOff}
          </button>
          <button
            className={config.verbose ? "lv-btn active" : "lv-btn"}
            onClick={() =>
              setConfig((prev) => ({
                ...prev,
                verbose: true,
              }))
            }
          >
            {L.config.verboseOn}
          </button>
        </div>
      </div>

      {/* Module Directory */}
      <div className="field">
        <label>{L.config.moduleDir}</label>
        <input
          type="text"
          value={config.moduledir}
          placeholder={DEFAULT_CONFIG.moduledir}
          onChange={(e) =>
            setConfig((prev) => ({
              ...prev,
              moduledir: e.target.value,
            }))
          }
        />
      </div>

      {/* Temp Directory */}
      <div className="field">
        <label>{L.config.tempDir}</label>
        <input
          type="text"
          value={config.tempdir}
          placeholder="(auto-select if empty)"
          onChange={(e) =>
            setConfig((prev) => ({
              ...prev,
              tempdir: e.target.value,
            }))
          }
        />
      </div>

      {/* Mount Source */}
      <div className="field">
        <label>{L.config.mountSource}</label>
        <input
          type="text"
          value={config.mountsource}
          placeholder={DEFAULT_CONFIG.mountsource}
          onChange={(e) =>
            setConfig((prev) => ({
              ...prev,
              mountsource: e.target.value,
            }))
          }
        />
      </div>

      {/* Log File */}
      <div className="field">
        <label>{L.config.logFile}</label>
        <input
          type="text"
          value={config.logfile}
          placeholder={DEFAULT_CONFIG.logfile}
          onChange={(e) =>
            setConfig((prev) => ({
              ...prev,
              logfile: e.target.value,
            }))
          }
        />
      </div>

      {/* Partitions */}
      <div className="field">
        <label>{L.config.partitions}</label>
        <input
          type="text"
          value={partitionInput}
          placeholder="mi_ext,my_stock"
          onChange={(e) => setPartitionInput(e.target.value)}
        />
      </div>

      <div className="actions">
        <button onClick={loadConfig} disabled={configLoading || configSaving}>
          {L.config.reload}
        </button>
        <button className="primary" onClick={saveConfig} disabled={configSaving || configLoading}>
          {configSaving ? "Saving..." : L.config.save}
        </button>
      </div>

      <p className="path">
        {L.config.pathLabel}: {CONFIG_PATH}
      </p>
    </div>
  );

  const renderRulesTab = () => (
    <div className="card">
      <h2>{L.rules.title}</h2>
      <p className="hint">{L.rules.desc}</p>
      {rulesLoading && <p className="hint">Loading...</p>}
      {rulesMessage && <p className="hint">{rulesMessage}</p>}

      <div className="rules-table">
        <div className="rules-header">
          <span style={{ flex: 2 }}>{L.rules.pathHeader}</span>
          <span style={{ flex: 1 }}>{L.rules.modeHeader}</span>
          <span style={{ width: "60px" }}>{L.rules.actionHeader}</span>
        </div>
        {rules.map((rule, idx) => (
          <div className="rule-row" key={idx}>
            <input
              type="text"
              style={{ flex: 2 }}
              value={rule.path}
              onChange={(e) => {
                const newRules = [...rules];
                newRules[idx].path = e.target.value;
                setRules(newRules);
              }}
            />
            <select
              style={{ flex: 1 }}
              value={rule.mode}
              onChange={(e) => {
                const newRules = [...rules];
                newRules[idx].mode = e.target.value as RuleMode;
                setRules(newRules);
              }}
            >
              <option value="overlay">{L.rules.modeOverlay}</option>
              <option value="bind">{L.rules.modeBind}</option>
            </select>
            <button
              className="delete-btn"
              style={{ width: "60px" }}
              onClick={() => {
                const newRules = rules.filter((_, i) => i !== idx);
                setRules(newRules);
              }}
            >
              X
            </button>
          </div>
        ))}
      </div>

      <div className="actions">
        <button
          onClick={() => {
            setRules([...rules, { path: "", mode: "overlay" }]);
          }}
        >
          {L.rules.add}
        </button>
        <div style={{ flex: 1 }}></div>
        <button onClick={loadRules} disabled={rulesLoading || rulesSaving}>
          {L.rules.reload}
        </button>
        <button className="primary" onClick={saveRules} disabled={rulesLoading || rulesSaving}>
          {rulesSaving ? "Saving..." : L.rules.save}
        </button>
      </div>
    </div>
  );

  const renderLogTab = () => {
    return (
      <div className="card">
        <h2>{L.logs.title}</h2>

        <div className="field">
          <label>{L.logs.select}</label>
          <div className="log-select-row">
            <select
              value={logSelection}
              onChange={(e) => setLogSelection(e.target.value as LogSelection)}
            >
              <option value="current">{L.logs.current}</option>
              <option value="old">{L.logs.old}</option>
            </select>

            <button className="refresh-btn" onClick={loadLog} disabled={logLoading}>
              {logLoading ? "Loading..." : L.logs.refresh}
            </button>
          </div>
        </div>

        {logError && <p className="error">{logError}</p>}

        <pre className="log-view">
          {logLoading && !logContent ? "Loading..." : logContent || L.logs.empty}
        </pre>
      </div>
    );
  };

  return (
    <div className="app-root">
      {/* top bar with language selector */}
      <div className="top-bar">
        <div className="title">Magic Mount</div>

        <select className="lang-select" value={lang} onChange={handleLangChange}>
          <option value="en">English</option>
          <option value="zh">中文</option>
        </select>
      </div>

      <div className="app-main">
        {activeTab === "config" && renderConfigTab()}
        {activeTab === "rules" && renderRulesTab()}
        {activeTab === "log" && renderLogTab()}
      </div>

      {/* bottom tabs */}
      <div className="bottom-bar">
        <button
          className={activeTab === "config" ? "tab-btn active" : "tab-btn"}
          onClick={() => setActiveTab("config")}
        >
          {L.tabs.config}
        </button>
        <button
          className={activeTab === "rules" ? "tab-btn active" : "tab-btn"}
          onClick={() => setActiveTab("rules")}
        >
          {L.tabs.rules}
        </button>
        <button
          className={activeTab === "log" ? "tab-btn active" : "tab-btn"}
          onClick={() => setActiveTab("log")}
        >
          {L.tabs.logs}
        </button>
      </div>
    </div>
  );
};

export default App;